### ISSUE TITLE
grid glitch in program page

### ISSUE THREAD

**Issue by garrett-laroy-johnson** [parkerdavis1/CCAM#2]
tiny grid glitch when components split across two rows: 

![image](https://github.com/parkerdavis1/CCAM/assets/6713092/2b34dc99-4cae-42aa-b2df-5a9e9192bc20)

**Comment by parkerdavis1** [comment]
Fixing the grid glitch is easy enough but keeping these dashed lines in the right place and the right size is a surprisingly difficult chestnut to crack ❄️🪵🔥🥜🌰🎄

**Comment by parkerdavis1** [comment]
Grid glitch is fixed but I haven't yet come up with a non-convoluted/brittle way to put not-connecting dashed dividers between multi-row grid with 1rem of padding everywhere.

**Comment by parkerdavis1** [comment]
The dashed borders are a surprisingly formidable problem. I have one more idea that I could explore with grid gap masking letting the dashed border background shine through then somehow have squares of tan background overlay the corners to create the breaks in the lines. But what to do when a row does not hold three cards...

Open to changing the design to make it more simple code-wise ;) not entirely sure what I'm imagining. No dashed borders between program cards? That'd be easy. ;)

🤙

**Comment by parkerdavis1** [comment]
Here is an option using a weird textured background technique. The leftover space is textured, whoops, but kinda cool. Might be able to work around that. Doesn't *quite* work because all the borders touch in the corners, instead of having 1rem padding. The borders extend beyond the top and to the sides unfortunately. Again, I'm not sure how to deal with this.

<img width="460" alt="Screenshot 2024-01-06 at 11 11 44 AM" src="https://github.com/parkerdavis1/CCAM/assets/92223355/41c56ce4-8372-4511-b7ff-165620fea41f">

Here it is with no dashed border between items. Not as consistent with everything else but simple, clean, consistent, not breakable.
<img width="468" alt="Screenshot 2024-01-06 at 11 15 08 AM" src="https://github.com/parkerdavis1/CCAM/assets/92223355/7a4039e9-d586-4ac7-9c2d-e9068624b00c">

**Comment by garrett-laroy-johnson** [comment]
I like the first one with the grid filler!

**Comment by parkerdavis1** [comment]
I freakin' CRACKED IT. Dashed grid lines (a la original design) incoming. 

<img width="1445" alt="Screenshot 2024-01-15 at 5 28 55 AM" src="https://github.com/parkerdavis1/CCAM/assets/92223355/f3be7229-af75-488b-838c-6cb18561932e">

**Comment by parkerdavis1** [comment]
Re @garrett-laroy-johnson 
The unexpected checkerboard texture is cool but there are some undesirable aspects of that approach where depending on your exact screensize the borders might be solid lines or some other weirdness. I'll go ahead and put the lines in with the approach I figured out this morning sometime this week.

**Comment by parkerdavis1** [comment]
Implemented with 8205453f1caec1540a0ffcf1bd6cc178615e4f39
