### ISSUE TITLE
Forms?

### ISSUE THREAD

**Issue by garrett-laroy-johnson** [parkerdavis1/CCAM#29]
We have several programs upcoming that will require RSVP or submitting an application to participate.

In the past I have always used Google Forms. They allow for a bit more customization these days, which is nice, and it compiles to a google sheet, which is convenient since CCAM is already a bit sunk into the GDrive ecosystem. What's more, the data is easily accessible via an interface many are already familiar with. 

I'm wondering if: 

1 there is a design preference for how Google Forms are used (are they embedded or linked?)

or 

2. if there is a good argument for using a bespoke but lightweight form kit that is fully integrated w the web ui.

**Comment by garrett-laroy-johnson** [comment]
That makes sense. 

Speaking of, is there a link / button component that we could use?

**Comment by parkerdavis1** [comment]
Building bespoke forms would not be terribly difficult, depending on the needs of the form, but building something that allows **y’all** to easily create a robust form sounds like too much at this point in time. it feels like there are too many little gotchas. Depends on the needs of your forms though, and how you want to be able to work with the data afterwards. I don’t know of any free open-source easy form builders that allow for full customization off the top of my head, maybe they’re out there though. Yeah, this forms question could definitely be something to revisit later, because it would definitely be more profesh to have them built in to the site.

yeah I'll make a little dashed outline button component you can use for stuff. 

If you don't want a button you can always do 
```[Click here to register](https://register.camm.world)```
